# Generated by Django 3.1.7 on 2021-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=40)),
                ('time_stamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
