# Generated by Django 3.1.7 on 2021-03-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment',
        ),
    ]
