# Generated by Django 3.1.7 on 2021-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment',
            field=models.TextField(default=0, max_length=5000),
        ),
    ]
