# Generated by Django 3.1.7 on 2021-03-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p',
        ),
    ]
