# Generated by Django 3.1.7 on 2021-03-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time_stamp',
        ),
    ]
